services:
  backend:
    image: blyndon/ebook-metadata-extractor-be:latest
    ports:
      - "8080:8080"
    environment:
      - OPENAI_MODEL=gpt-3.5-turbo
      - MAX_TOKEN_COUNT=1500
      - PROMPT_FILE=./assets/prompt.txt
      - TARGET_FILE_EXTENSION=.json
      - SOURCE_DIR=/data/sourceDir
      - TARGET_DIR=/data/targetDir
      - PERSIST_METADATA=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8080
      - ALLOWED_ORIGIN=http://localhost:3000
    volumes:
      - ./data/sourceDir:/data/sourceDir
      - ./data/targetDir:/data/targetDir
    networks:
      - app-network

  frontend:
    image: blyndon/ebook-metadata-extractor-fe:latest
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_PROTOCOL=http
      - REACT_APP_API_HOSTNAME=backend
      - REACT_APP_API_PORT=8080
      - REACT_APP_API_BASE_PATH=  # Leave empty or specify a path if needed
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
